#ifndef _INTERCEPTOR_MACRO_H
#define _INTERCEPTOR_MACRO_H
#include "indexInterceptor.h"

NAME_SPACE_START(myUtil)
#define REFLEX_INPERCEPTOR_DECLARE REGISTER_REFLEX(IndexInterceptor)
NAME_SPACE_END()

#endif //!_INTERCEPTOR_MACRO_H
