import("//config.gni")

action("ulgui_shader_glsl") {
  script = "//build/copy.py"
  inputs = [ "shader" ]
  outputs = [ "$target_gen_dir/shader" ]
  args = [
    "--input", rebase_path("shader", root_build_dir),
    "--dest", rebase_path("$target_gen_dir", root_build_dir),
  ]
}

shared_library("BaseGraphics") {
  sources = [
    "src/abstractAbility.cpp",
    "src/baseGraphics.cpp",
    "src/brush.cpp",
    "src/coord.cpp",
    "src/font.cpp",
    "src/pen.cpp",
    "src/renderer.cpp",
    "//src/glad.c",
  ]
  configs += [
    "$third_part/glm:glm_config",
    "$ulgui_path:base_config",
    "$ulgui_path:event_config",
    "$ulgui_path:BaseGraphics_config",
    "$utils_path/Shader:shader_config",
  ]
  public_deps = [
    ":ulgui_shader_glsl",
    "$utils_path/Shader:shader_shared",
  ]
}
