import("//config.gni")
import("//utils/test_config.gni")

config("base_config") {
  include_dirs = [ "include" ]
  defines = [
    "GLFW_INCLUDE_NONE", # OpenGL 头由 glad 提供，禁止 glfw 再引入 <GL/gl.h>
  ]
}

config("event_config") {
  include_dirs = [ "events/include" ]
}

config("BaseGraphics_config") {
  include_dirs = [
    "base/include",
    "//include",  # glad/glad.h
  ]
}

config("components_config") {
  include_dirs = [ "components/include" ]
}

test_executable("ULGuiTest") {
  include_dirs = [ "//include" ]
  sources = [
    "test/ULGui_test.cpp",
  ]
  configs = [
    ":base_config",
    ":BaseGraphics_config",
    ":components_config",
    ":event_config",
    "$third_part/glm:glm_config",
  ]
  libs = [ "dl", "GL" ]
  so_deps = [
    ":Window",
    "base:BaseGraphics",
    "canvas:CanvasKit",
    "components:Components",
    "events:Events",
    "$third_part/glfw:glfw",
    "$utils_path/Shader:shader_shared",
  ]

  output_dir = "$target_gen_dir"
}

shared_library("Window") {
  sources = [
    "src/abstractWidget.cpp",
    "src/ULGuiColor.cpp",
    "src/widget.cpp",
  ]
  configs += [
    ":base_config",
    ":BaseGraphics_config",
    ":components_config",
    ":event_config",
    "$third_part/glm:glm_config",
    "$utils_path/Shader:shader_config",
  ]
  public_deps = [
    "components:Components",
    "$third_part/glfw:glfw",
    "$utils_path/Shader:shader_shared",
  ]
}

group("ULGui_test") {
  deps = [
  ]
}