import("//build/cxx_config.gni")
import("//config.gni")
import("//utils/test_config.gni")

util_sources = [
  "src/Ini.cpp",
  "src/MD5.cpp",
  "src/Util.cpp",
]
config("util_config") {
  include_dirs = [
    "include",
    "$utils_path/Log",
  ]
}

static_library("util_static") {
  public_configs = [ ":util_config" ]
  sources = util_sources
  if (is_use_log_client) {
    so_deps += [ "$utils_path/Log:log_client_shared" ]
  }
}

shared_library("util_shared") {
  public_configs = [ ":util_config" ]
  sources = util_sources
}

test_executable("UtilTest") {
  sources = [ "test/Util_test.cpp" ]
  deps = [
    ":util_static",
    "$third_part/googletest:gtest",
  ]
}
